### ISSUE TITLE
[IMP] TO-DO

### ISSUE THREAD

**Issue by PseudoCodeNerd** [PseudoCodeNerd/elite2020-creative-webd#1]
### Days Left till submission : 7 

**Overview**
*Illuminati vs KKK* 
- Frontend for propagating the advantages of joining *'The Resistance Fighting Force*'
- Backend for recruiting people for positions in the *RFF*.

#### creativity <> implementation <> code quality <> design (minimal)
---
**Basic + lipsum**
- [x]  Landing Page
- [x]  About Page 
- [x]  Perks Page
- [x]  Jobs Page
- [x]  Apply Page

**Backend (Priority)**
> Django !
- [x]  Store applications and open jobs in DB
- [x]  Admin / Applicant roles; authentication + authorisation
- [x]  Admin perms : edit job list, accept/reject apps
- [x] Applicant perms : edit personal info, apply for jobs, see status of job apps

**Frontend (Only if time available)**
In increasing order of likeliness of doing.
- [x] Not submit invalid input in forms
- [x] Validate user input
- [x] Application form captcha enabled
- [x] Search + filter for jobs for various params

---

**Finally deploy to PythonAnywhere**

**Comment by mdvsh** [comment]
Everything looks alright.
Closing.
